source 'https://rubygems.org'
gem 'sprockets'
gem 'dashing'
gem 'twitter', '>= 5.9.0'
gem 'circleci'
gem 'httparty'
gem 'google-api-client', '>= 0.8'
gem 'slack-ruby-client', '~> 0.8.0'
gem 'stock_quote', '~> 2.0.0'
gem 'forecast_io'
gem 'nest_thermostat'
gem 'bart', github: 'cannuk/bart', branch: 's-update-destination-query'
gem 'rMeetup'
gem 'chronic'
gem 'hipchat'
gem 'mechanize'
gem 'nokogiri'
gem 'muni', '~> 0.0.5'
