source 'https://rubygems.org'
gem 'dashing'
gem 'twitter', '>= 5.9.0'
gem 'circleci'
gem 'httparty'
gem 'google-api-client', '>= 0.8'
gem 'slack-ruby-client', '~> 0.8.0'
gem 'stock_quote', '~> 1.3.0'
gem 'darksky'

